[workspace]
members = [
    "libs/au"
]
resolver = "2"

[workspace.dependencies]
au = { path = "libs/au" }
automerge = { version = "0.5.9" }
serde = { version = "1.0.197" }
time = {  version = "0.3" }
thiserror = { version = "1.0.58" }